import Head from 'next/head';

const PrivacyPolicy = () => {
  return (
    <div className="min-h-scree py-12 px-4 sm:px-6 lg:px-8 text-gray-700">
      <Head>
        <title>Zennova Privacy Policy</title>
        <meta name="description" content="Zennova Privacy Policy" />
      </Head>
      <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
        <h1 className="text-3xl font-bold mb-6 text-center">Privacy Policy</h1>
        <p className="text-sm text-gray-600 mb-4">Updated at 2025-01-01</p>

        <p className="mb-4">
          Zennova (“we,” “our,” or “us”) is committed to protecting your privacy. This privacy policy (“Privacy Policy” or, this “Policy”) explains how your personal information is collected, used, and disclosed by Zennova through the Platform.
        </p>
        <p className="mb-4">
          By accessing or using our Platform and availing of our Products, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Use.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Definitions & Key Terms</h2>
        <p className="mb-4">To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:</p>
        <ul className="list-disc pl-6 mb-4">
          <li><strong>“Cookie”</strong>: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
          <li><strong>“Company,” “we,” “us,” or “our”</strong>: Zennova Technologies Private Limited, a company incorporated under the laws of India, and having its registered office at Palash Basti, House No451, Palash Basti Road,barsala, 784110, Bogipukhuri, Sonitpur, Alisinga, Assam, India and/or its affiliates.</li>
          <li><strong>“Customer”</strong>: the company, organization, or person that signs up to use the Zennova Product to manage the relationships with your consumers or product users.</li>
          <li><strong>“Device”</strong>: any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Zennova and use the products.</li>
          <li><strong>“IP address”</strong>: every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
          <li><strong>“Personnel”</strong>: those individuals who are employed by Zennova or are under contract to perform a function on our behalf.</li>
          <li><strong>“Personal Data”</strong>: any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person.</li>
          <li><strong>“Platform”</strong>: the Website, any mobile application, and other portal developed by us to provide the Product.</li>
          <li><strong>“Product”</strong>: the offerings provided by or made available to you by Zennova from time to time.</li>
          <li><strong>“Terms of Use”</strong>: the terms and conditions applicable to the Platform, as may be modified from time to time.</li>
          <li><strong>“Third-party service”</strong>: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products we think may interest you.</li>
          <li><strong>“User Information”</strong>: information pertaining to you and shall include your Personal Data.</li>
          <li><strong>“Website”</strong>: Zennova’s site, which can be accessed via https://www.zennova.in, and its associated subdomains.</li>
          <li><strong>“You”</strong>: a person or entity that is registered with Zennova to use the Products.</li>
        </ul>
        <p className="mb-4">
          In addition to the above, any capitalized term used herein below, but not specifically defined, shall have the meaning assigned in the Terms of Use or in the relevant portion of this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">What Information Do We Collect?</h2>
        <p className="mb-4">
          We collect information from you when you visit our Platform, register on our Platform, place an order, subscribe to our newsletter, respond to a survey, or fill out a form.
        </p>
        <ul className="list-disc pl-6 mb-4">
          <li>Name / Username</li>
          <li>Phone Numbers</li>
          <li>Email Addresses</li>
          <li>Password</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">How Do We Use The Information We Collect?</h2>
        <p className="mb-4">Any of the information we collect from you may be used in one of the following ways:</p>
        <ul className="list-disc pl-6 mb-4">
          <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
          <li>To improve our Platform (we continually strive to improve our offerings based on the information and feedback we receive from you)</li>
          <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
          <li>To process transactions</li>
          <li>To administer a contest, promotion, survey, or other site feature</li>
          <li>To send periodic emails</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">When Does Zennova Use End User Information from Third Parties?</h2>
        <p className="mb-4">
          Zennova will collect User Information necessary to provide the Zennova products to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">When Does Zennova Use Customer Information from Third Parties?</h2>
        <p className="mb-4">
          We receive some information from third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Zennova customer, we receive information from a third party that provides automated fraud detection services to Zennova. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Do We Share the Information We Collect with Third Parties?</h2>
        <p className="mb-4">
          We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale, or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
        </p>
        <p className="mb-4">
          We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the Platform, database storage and management, e-mail management, storage marketing, credit card processing, customer service, and fulfilling orders for products you may purchase through the Platform. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
        </p>
        <p className="mb-4">
          We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the Platform in a shared location, and type of the device used to visit the Platform. They may aggregate information about our advertising and what you see on the Platform and then provide auditing, research, and reporting for us and our advertisers.
        </p>
        <p className="mb-4">
          We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules, and regulations.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Where and When Is Information Collected from Customers and End Users?</h2>
        <p className="mb-4">
          Zennova will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">How Do We Use Your Email Address?</h2>
        <p className="mb-4">
          By submitting your email address on the Platform, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">How Long Do We Keep Your Information?</h2>
        <p className="mb-4">
          We take reasonable steps to ensure that any information that we collect from you is available only for so long as is necessary for the purpose for which it is processed, or longer if required under any applicable law, subject to appropriate safeguards. Please note that we ensure that all other information collected and stored is anonymized and aggregated in an irreversible manner. Furthermore, you explicitly consent and agree that we will be entitled to use such anonymized data or information freely, without any restrictions other than those set out under applicable law. Once any portion of the User Information collected by us is no longer necessary for the purpose for which it is processed, or is no longer required under any applicable law, whichever is later, such User Information shall be forthwith deleted, without retention of any copies.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">How Do We Protect Your Information?</h2>
        <p className="mb-4">
          We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Zennova or guarantee that your information on the Product may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
        </p>
        <p className="mb-4">
          The collection, usage, and sharing of User Information by us shall be in compliance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and other applicable laws.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Could My Information Be Transferred to Other Countries?</h2>
        <p className="mb-4">
          Zennova is incorporated in India. Information collected via our Platform, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily and expressly consent to the trans-border transfer and hosting of such information.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Is the Information Collected Through the Zennova Secure?</h2>
        <p className="mb-4">
          We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes, or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Can I Update or Correct My Information?</h2>
        <p className="mb-4">
          The rights you have to request updates or corrections to the information Zennova collects depend on your relationship with Zennova. Personnel may update or correct their information as detailed in our internal company employment policies.
        </p>
        <p className="mb-4">
          Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us at privacy@zennova.in in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes, and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change, or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.
        </p>
        <p className="mb-4">
          You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed, or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.
        </p>
        <p className="mb-4">
          If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Personnel</h2>
        <p className="mb-4">
          If you are a Zennova worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.
        </p>
        <p className="mb-4">
          You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes, and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change, or deletion.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Sale of Business</h2>
        <p className="mb-4">
          We reserve the right to transfer information to a third party in the event of a sale, merger, or other transfer of all or substantially all of the assets of Zennova or any of its Corporate Affiliates (as defined herein), or that portion of Zennova or any of its Corporate Affiliates to which the Product relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization, or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Affiliates</h2>
        <p className="mb-4">
          We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by, or is under common control with Zennova, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Your Consent</h2>
        <p className="mb-4">
          We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our Platform, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Links to Other Websites</h2>
        <p className="mb-4">
          This Privacy Policy applies only to the Products. The Products may contain links to other websites not operated or controlled by Zennova. We are not responsible for the content, accuracy, or opinions expressed in such websites, and such websites are not investigated, monitored, or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Products to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our Platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
        </p>
        <p className="mb-4">
          We may display, include, or make available third-party content (including data, information, applications, and other products) or provide links to third-party websites ("Third-Party Website"). You acknowledge and agree that Zennova shall not be responsible for any Third-Party Website, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. Zennova does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Websites. Third-Party Websites and links thereto are provided solely for your convenience and you shall access and use them entirely at your own risk and subject to such third parties' terms and conditions.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Tracking Technologies</h2>
        <p className="mb-4">
          <strong>Cookies:</strong> We use Cookies to enhance the performance and functionality of our Platform but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the Platform as we would not be able to remember that you had logged in previously.
        </p>
        <p className="mb-4">
          <strong>Sessions:</strong> Zennova uses "Sessions" to identify the areas of our Platform that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Cookies</h2>
        <p className="mb-4">
          Zennova uses "Cookies" to identify the areas of our Platform that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our Platform but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the Platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our Platform correctly or at all. We never place Personally Identifiable Information in Cookies.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Blocking and Disabling Cookies and Similar Technologies</h2>
        <p className="mb-4">
          Wherever you're located, you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our Platform from functioning properly, and you may not be able to fully utilize all of its features. You should also be aware that you may also lose some saved information (e.g., saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Remarketing Services</h2>
        <p className="mb-4">
          We use remarketing services. In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they are “following” people around the internet by serving ads on the websites and platforms they use most.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Payment Details</h2>
        <p className="mb-4">
          In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Kids' Privacy</h2>
        <p className="mb-4">
          We collect information from kids under the age of 18 just to better manage our Platform. If you are a parent or guardian and you are aware that your child has provided us with Personal Data without your permission, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 18 without verification of parental consent, we take steps to remove that information from our servers.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to Our Privacy Policy</h2>
        <p className="mb-4">
          We reserve the right to change or update this Privacy Policy at any time. Such changes shall be effective immediately upon posting on this Platform. Your continued access and/or use of the Platform following any such change constitutes your agreement to follow and be bound by this Privacy Policy, as updated or modified. For this reason, we encourage you to review this Privacy Policy each time you access and use the Platform. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Facebook Pixel</h2>
        <p className="mb-4">
          Facebook pixel is an analytics tool that allows you to measure the effectiveness of your advertising by understanding the actions people take on your website. You can use the pixel to: Make sure your ads are shown to the right people. Facebook pixel may collect information from your device when you use the service. Facebook pixel collects information that is held in accordance with its Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Governing Law</h2>
        <p className="mb-4">
          This Privacy Policy is governed by the laws of India. Your use of the Platform may also be subject to other local, state, national, or international laws.
        </p>
        <p className="mb-4">
          This Privacy Policy is intended for users within the territory of India and governs your rights as per applicable law within the territory of India. However, in the event you fall under a jurisdiction outside the purview of Indian law, we will not be liable for any claim, action, and/or right initiated/exercised by you as per the extant laws of that jurisdiction. Therefore, we request you to kindly use the Product or access the Platform accordingly.
        </p>
        <p className="mb-4">
          By using Zennova or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our Platform, or use our products. Continued use of the Platform, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
        <p className="mb-4">Don't hesitate to contact us if you have any questions.</p>
        <p className="mb-4">Via Email: privacy@zennova.in</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Nodal Grievance Redressal Officer</h2>
        <p className="mb-4">
          As required under the Information Technology Act, 2000 and rules made thereunder, for the purposes of redressing any complaints, you may contact our nodal grievance redressal officer whose name and contact details are provided below:
        </p>
        <p className="mb-4">
          <strong>NAME:</strong> Mr. Ibne Alam Khan<br />
          <strong>Address:</strong> Palash Basti, House No451, Palash Basti Road,barsala, Bogipukhuri, Sonitpur, Alisinga, Assam, India, 784112<br />
          <strong>TEL:</strong> +91 9864972356<br />
          <strong>EMAIL:</strong> support@zennova.in
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;